import {
    Card,
    CardContent,
  } from "@/components/ui/card";
  
  interface Props {
    revenue: string;
    netIncome: string;
    assets: string;
    recommendation: string;
  }
  
  export default function FinancialDashboard({
    revenue,
    netIncome,
    assets,
    recommendation,
  }: Props) {
    return (
      <div className="grid gap-4 md:grid-cols-4">
  
        {/* Revenue */}
  
        <Card
          className="
            border-zinc-800
            bg-zinc-950
            transition
            hover:border-zinc-700
          "
        >
          <CardContent className="p-6">
  
            <p className="text-xs uppercase tracking-[0.22em] text-zinc-500">
              Revenue
            </p>
  
            <p className="mt-3 text-2xl font-semibold text-white">
              {revenue}
            </p>
  
            <p className="mt-2 text-sm text-zinc-500">
              Total reported revenue
            </p>
  
          </CardContent>
        </Card>
  
        {/* Net Income */}
  
        <Card
          className="
            border-zinc-800
            bg-zinc-950
            transition
            hover:border-zinc-700
          "
        >
          <CardContent className="p-6">
  
            <p className="text-xs uppercase tracking-[0.22em] text-zinc-500">
              Net Income
            </p>
  
            <p className="mt-3 text-2xl font-semibold text-white">
              {netIncome}
            </p>
  
            <p className="mt-2 text-sm text-zinc-500">
              Earnings after expenses
            </p>
  
          </CardContent>
        </Card>
  
        {/* Assets */}
  
        <Card
          className="
            border-zinc-800
            bg-zinc-950
            transition
            hover:border-zinc-700
          "
        >
          <CardContent className="p-6">
  
            <p className="text-xs uppercase tracking-[0.22em] text-zinc-500">
              Total Assets
            </p>
  
            <p className="mt-3 text-2xl font-semibold text-white">
              {assets}
            </p>
  
            <p className="mt-2 text-sm text-zinc-500">
              Assets identified by AI
            </p>
  
          </CardContent>
        </Card>
  
        {/* Recommendation */}
  
        <Card
          className="
            border-zinc-800
            bg-zinc-950
            transition
            hover:border-zinc-700
          "
        >
          <CardContent className="p-6">
  
            <p className="text-xs uppercase tracking-[0.22em] text-zinc-500">
              Recommendation
            </p>
  
            <p className="mt-3 text-2xl font-semibold text-white">
              {recommendation}
            </p>
  
            <p className="mt-2 text-sm text-zinc-500">
              Generated by AI analysis
            </p>
  
          </CardContent>
        </Card>
  
      </div>
    );
  }